import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.75
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGL Nerd Font Mono"
size=18
